### ISSUE TITLE
Make a Markdown Readme for project

### ISSUE THREAD

**Issue by dataist** [sims226/rivets#1]
Every project should have a readme.md 

see cheatsheet here: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by sims226** [comment]
Agreed, knew that at one time, should've remembered...

I've added a quick draft written between activities at niece-in-law's graduation BBQ. I'll edit/update/improve as I go.

**Comment by dataist** [comment]
I think your section markers need a space between them and the section headers to be rendered properly. Also, lets get into the PR workflow even for stuff like updating readmes

**Comment by dataist** [comment]
Also, you can preview your markdown in a place like [this](http://markdownlivepreview.com) or use an IDE that can preview it for you.

**Comment by sims226** [comment]
I have a Markdown Preview in my text editor, just never looked for it. My readme will be muy stylish on next commit.
